spring.application.name=VoteSystem

# Server port
server.port=${PROD_SERVER_PORT:80}

# Database
spring.datasource.url=jdbc:mysql://${PROD_DB_HOST:localhost}:${PROD_DB_PORT:3306}/${PROD_DB_NAME:votesystem}
spring.datasource.username=${PROD_DB_USERNAME:test}
spring.datasource.password=${PROD_DB_PASSWORD:1234}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# Server sql init
spring.sql.init.mode=always
spring.sql.init.schema-locations=classpath:schema.sql

# Swagger
springdoc.api-docs.path=/api-docs
springdoc.swagger-ui.path=/api
springdoc.swagger-ui.disable-swagger-default-url=true

# Server URL
server.url=${PROD_SERVER_URL:http://localhost}
